### ISSUE TITLE
make init error

### ISSUE THREAD

**Issue by yangboz** [xlp0/DockerizedMediaWiki#5]
after make an empty mountPoint directory, after running make init. it thrown:

```
xbdserver@xbdserver-HP-Z800:~/DockerizedPKC$ mkdir mountPoint
xbdserver@xbdserver-HP-Z800:~/DockerizedPKC$ make init
./up.sh
linux-gnu has Docker version 20.10.7, build 20.10.7-0ubuntu1~18.04.2 installed
Loaded environmental variable: PORT_NUMBER=5320
Please type in the Administrative(root) password of the machine that you are installing PKC service when asked...
Stopping dockerizedpkc_mediawiki_1 ... done
Stopping dockerizedpkc_database_1  ... done
Removing dockerizedpkc_mediawiki_1 ... done
Removing dockerizedpkc_database_1  ... done
Removing network dockerizedpkc_default
Creating network "dockerizedpkc_default" with the default driver
Creating dockerizedpkc_database_1 ... done
Creating dockerizedpkc_mediawiki_1 ... done
It needs to wait for at least 3 seconds before launching the php /var/www/html/maintenance/update.php script
MediaWiki 1.35.2 Updater

Your composer.lock file is up to date with current dependencies!
Wikimedia\Rdbms\DBConnectionError from line 1420 of /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Cannot access the database: Unknown error (database:3306)
#0 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(934): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#1 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(901): Wikimedia\Rdbms\LoadBalancer->getServerConnection(0, 'my_wiki', 4)
#2 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1046): Wikimedia\Rdbms\LoadBalancer->getConnection(-2, Array, 'my_wiki', 4)
#3 /var/www/html/maintenance/includes/Maintenance.php(1368): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef(-2, Array, 'my_wiki')
#4 /var/www/html/maintenance/update.php(141): Maintenance->getDB(-2)
#5 /var/www/html/maintenance/doMaintenance.php(107): UpdateMediaWiki->execute()
#6 /var/www/html/maintenance/update.php(253): require_once('/var/www/html/m...')
#7 {main}
Makefile:26: recipe for target 'init' failed
make: *** [init] Error 1
```

any idea?

**Comment by yangboz** [comment]
tried to run  up.sh, it thrown: 

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: read init-p: connection reset by peer: unknown
